/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Medicare index: the deduplicated patient index produced by the archive PHI
 * pipeline (data/medicare_index.json, generated by
 * `_medica_scan_report/PHI/medicare_index.csv`).
 *
 * The JSON is the source of truth and is re-imported on boot by
 * server/services/medicareService.ts whenever its fingerprint changes. The
 * fingerprint covers the JSON *and* an import rule version, so tightening a rule (e.g.
 * the owner's expiry window) re-imports even when the JSON bytes are unchanged. The
 * tables exist so the index is actually queryable — sorted, filtered and
 * searchable — rather than shipping 3.5k rows to the browser to sort there.
 *
 * `expiry_best_date` only ever holds a value that passed the owner's rule
 * (src/utils/medicareExpiry.ts: MM/YY or MM/YYYY, 09/2026 through 09/2031). Rejected
 * detections are cleared at import, so the table cannot serve an irrelevant expiry.
 *
 * Uses CREATE TABLE IF NOT EXISTS so it is safe to run on every boot.
 */

import type { Database as DatabaseType } from 'better-sqlite3';

export function runMigrations(db: DatabaseType): void {
  db.exec(`
    CREATE TABLE IF NOT EXISTS medicare_patients (
      patient_id            TEXT PRIMARY KEY,
      full_name             TEXT NOT NULL DEFAULT '',
      name_display          TEXT NOT NULL DEFAULT '',
      name_status           TEXT NOT NULL DEFAULT 'ok',
      name_flags            TEXT NOT NULL DEFAULT '',
      title                 TEXT NOT NULL DEFAULT '',
      surname               TEXT NOT NULL DEFAULT '',
      given_name            TEXT NOT NULL DEFAULT '',
      middle_names          TEXT NOT NULL DEFAULT '',
      dob_iso               TEXT NOT NULL DEFAULT '',
      sex                   TEXT NOT NULL DEFAULT '',
      medicare_number       TEXT NOT NULL DEFAULT '',
      medicare_valid        INTEGER,
      medicare_len          INTEGER NOT NULL DEFAULT 0,
      medicare_flags        TEXT NOT NULL DEFAULT '',
      mrn                   TEXT NOT NULL DEFAULT '',
      phone                 TEXT NOT NULL DEFAULT '',
      email                 TEXT NOT NULL DEFAULT '',
      address_full          TEXT NOT NULL DEFAULT '',
      suburb                TEXT NOT NULL DEFAULT '',
      state                 TEXT NOT NULL DEFAULT '',
      postcode              TEXT NOT NULL DEFAULT '',
      referrer              TEXT NOT NULL DEFAULT '',
      tests                 TEXT NOT NULL DEFAULT '',
      diagnoses             TEXT NOT NULL DEFAULT '',
      expiry_tokens         TEXT NOT NULL DEFAULT '',
      expiry_best_word      TEXT NOT NULL DEFAULT '',
      expiry_best_date      TEXT NOT NULL DEFAULT '',
      expiry_best_raw       TEXT NOT NULL DEFAULT '',
      expiry_best_precision TEXT NOT NULL DEFAULT '',
      has_expiry            INTEGER NOT NULL DEFAULT 0,
      record_count          INTEGER NOT NULL DEFAULT 0,
      confidence_best       TEXT NOT NULL DEFAULT '',
      doc_dates_range       TEXT NOT NULL DEFAULT '',
      source_files          TEXT NOT NULL DEFAULT '',
      needs_review          INTEGER NOT NULL DEFAULT 0,
      name_suspect          INTEGER NOT NULL DEFAULT 0,
      completeness          INTEGER NOT NULL DEFAULT 0,
      search_blob           TEXT NOT NULL DEFAULT ''
    );

    -- One row per (patient, source document) so the detail view can list every
    -- file a patient's data came from without parsing a delimited string.
    CREATE TABLE IF NOT EXISTS medicare_patient_sources (
      patient_id  TEXT NOT NULL,
      source_file TEXT NOT NULL,
      PRIMARY KEY (patient_id, source_file)
    );

    -- Tracks which build of the JSON is currently loaded, so a re-import only
    -- happens when the upstream pipeline actually produced new data.
    CREATE TABLE IF NOT EXISTS medicare_index_meta (
      id          INTEGER PRIMARY KEY CHECK (id = 1),
      fingerprint TEXT NOT NULL,
      row_count   INTEGER NOT NULL DEFAULT 0,
      loaded_at   TEXT NOT NULL DEFAULT (datetime('now'))
    );

    CREATE INDEX IF NOT EXISTS idx_medicare_number
      ON medicare_patients(medicare_number);
    CREATE INDEX IF NOT EXISTS idx_medicare_valid
      ON medicare_patients(medicare_valid);
    CREATE INDEX IF NOT EXISTS idx_medicare_surname
      ON medicare_patients(surname);
    CREATE INDEX IF NOT EXISTS idx_medicare_dob
      ON medicare_patients(dob_iso);
    CREATE INDEX IF NOT EXISTS idx_medicare_expiry_date
      ON medicare_patients(expiry_best_date);
    CREATE INDEX IF NOT EXISTS idx_medicare_name_status
      ON medicare_patients(name_status);
    CREATE INDEX IF NOT EXISTS idx_medicare_needs_review
      ON medicare_patients(needs_review);
    CREATE INDEX IF NOT EXISTS idx_medicare_sex
      ON medicare_patients(sex);
    CREATE INDEX IF NOT EXISTS idx_medicare_state
      ON medicare_patients(state);
    CREATE INDEX IF NOT EXISTS idx_medicare_sources_patient
      ON medicare_patient_sources(patient_id);
  `);
}
