#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  parseCharter,
  parseFrontMatter,
  normalizeText,
} from './charter-parser.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '../..');

const charterPath = path.join(repoRoot, 'PROJECT_CHARTER.md');
const stagesDir = path.join(repoRoot, 'docs/stages');
const indexReadmePath = path.join(stagesDir, 'README.md');

export function generateIndexContent(customRepoRoot = repoRoot) {
  const charterPath = path.join(customRepoRoot, 'PROJECT_CHARTER.md');
  const stagesDir = path.join(customRepoRoot, 'docs/stages');
  const charterContent = fs.readFileSync(charterPath, 'utf8');
  const charterStages = parseCharter(charterContent);

  // Discover all dossiers in docs/stages matching stage-*.md
  const files = fs.readdirSync(stagesDir);
  const dossierFiles = files.filter((f) => /^stage-(0[1-9]|[1-4][0-9]|5[0-5])-[a-z0-9-]+\.md$/.test(f));

  const dossiersByStage = new Map();

  for (const file of dossierFiles) {
    const fullPath = path.join(stagesDir, file);
    const content = fs.readFileSync(fullPath, 'utf8');
    const { meta } = parseFrontMatter(content);
    dossiersByStage.set(meta.stage, { ...meta, filename: file });
  }

  // Count statuses across all 55 stages
  const statusCounts = {
    complete: 0,
    'in-progress': 0,
    deferred: 0,
    'blocked-external': 0,
    'not-started': 0,
  };

  for (const cs of charterStages) {
    const d = dossiersByStage.get(cs.stage);
    const status = d ? d.status : 'not-started';
    if (statusCounts[status] !== undefined) {
      statusCounts[status]++;
    } else {
      statusCounts['not-started']++;
    }
  }

  const lines = [
    '# 55-Stage Execution Dossier Index',
    '',
    'This directory contains execution-ready dossiers for all 55 stages of `PROJECT_CHARTER.md`.',
    'Each dossier establishes verbatim SHA-256 hashed charter gates, explicit work breakdowns,',
    'owned paths, frozen contracts, fan-out plans, and machine-guarded acceptance evidence.',
    '',
    'This index is generated automatically by `scripts/stages/build-index.mjs` and enforced by',
    '`tests/stages.test.mjs`. Do not edit this file by hand.',
    '',
    '## Status Summary',
    '',
    '| Status | Count | Percentage | Description |',
    '|---|---|---|---|',
    `| Complete | ${statusCounts['complete']} | ${((statusCounts['complete'] / 55) * 100).toFixed(1)}% | Verified with inspectable evidence artifacts and passing gate |`,
    `| In Progress | ${statusCounts['in-progress']} | ${((statusCounts['in-progress'] / 55) * 100).toFixed(1)}% | Currently undergoing active implementation / verification |`,
    `| Deferred | ${statusCounts['deferred']} | ${((statusCounts['deferred'] / 55) * 100).toFixed(1)}% | Prior attempt paused or failed; preserved diagnostic for next sweep |`,
    `| Blocked External | ${statusCounts['blocked-external']} | ${((statusCounts['blocked-external'] / 55) * 100).toFixed(1)}% | Engineering complete; awaiting owner or third-party sign-off |`,
    `| Not Started | ${statusCounts['not-started']} | ${((statusCounts['not-started'] / 55) * 100).toFixed(1)}% | Greenfield implementation governed by stage dossier |`,
    `| **Total** | **55** | **100.0%** | **Full Project Charter Scope** |`,
    '',
    `*Authored dossiers on disk:* ${dossierFiles.length} / 55`,
    '',
    '## Stage Execution Matrix',
    '',
    '| # | Slug | Title | Status | Weight Area | Depends On | Blocks | External Gates | Dossier |',
    '|---|---|---|---|---|---|---|---|---|',
  ];

  for (const cs of charterStages) {
    const d = dossiersByStage.get(cs.stage);
    const stageNum = String(cs.stage).padStart(2, '0');
    const slug = d ? d.slug : cs.slug;
    const title = cs.title;
    const status = d ? d.status : 'not-started';
    const weightArea = d ? d.weight_area : '—';
    const dependsOn = d && Array.isArray(d.depends_on) && d.depends_on.length > 0 ? d.depends_on.join(', ') : 'none';
    const blocks = d && Array.isArray(d.blocks) && d.blocks.length > 0 ? d.blocks.join(', ') : 'none';
    const externalGates = d && Array.isArray(d.external_gates) && d.external_gates.length > 0 ? d.external_gates.join(', ') : 'none';
    const dossierLink = d ? `[${d.filename}](${d.filename})` : '*(pending authoring)*';

    lines.push(
      `| ${stageNum} | \`${slug}\` | ${title} | \`${status}\` | \`${weightArea}\` | ${dependsOn} | ${blocks} | ${externalGates} | ${dossierLink} |`
    );
  }

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Usage and Maintenance');
  lines.push('');
  lines.push('```powershell');
  lines.push('# Regenerate index from dossier front-matter:');
  lines.push('node scripts/stages/build-index.mjs --write');
  lines.push('');
  lines.push('# Check index synchronisation in CI:');
  lines.push('node scripts/stages/build-index.mjs --check');
  lines.push('```');
  lines.push('');

  return lines.join('\n');
}

export function main(customRepoRoot = repoRoot) {
  const args = process.argv.slice(2);
  const isCheck = args.includes('--check');
  const stagesDir = path.join(customRepoRoot, 'docs/stages');
  const indexReadmePath = path.join(stagesDir, 'README.md');

  const generated = generateIndexContent(customRepoRoot);

  if (isCheck) {
    if (!fs.existsSync(indexReadmePath)) {
      console.error(`ERROR: ${indexReadmePath} does not exist. Run with --write to generate.`);
      process.exit(1);
    }
    const existing = fs.readFileSync(indexReadmePath, 'utf8');
    if (normalizeText(existing) !== normalizeText(generated)) {
      console.error(`ERROR: ${indexReadmePath} is out of sync with dossier front-matter.`);
      console.error('Run: node scripts/stages/build-index.mjs --write');
      process.exit(1);
    }
    console.log('OK: docs/stages/README.md is synchronized with all dossiers.');
    process.exit(0);
  } else {
    // Write mode (default or --write)
    fs.writeFileSync(indexReadmePath, generated, { encoding: 'utf8' });
    console.log(`OK: Generated ${indexReadmePath}`);
    process.exit(0);
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(__filename)) {
  main();
}
